/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "var(--tertiary, #924700)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim, #ffb786)",
        "surface-container-high": "var(--surface-container-high, #e1e8fd)",
        "on-secondary": "var(--on-secondary, #ffffff)",
        "surface-container": "var(--surface-container, #e9edff)",
        "surface-variant": "var(--surface-variant, #dce2f7)",
        "secondary-fixed": "var(--secondary-fixed, #dce2f3)",
        "on-secondary-fixed": "var(--on-secondary-fixed, #151c27)",
        "surface-tint": "var(--surface-tint, #005ac2)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim, #c0c7d6)",
        "secondary": "var(--secondary, #585f6c)",
        "on-tertiary": "var(--on-tertiary, #ffffff)",
        "outline-variant": "var(--outline-variant, #c2c6d6)",
        "tertiary-fixed": "var(--tertiary-fixed, #ffdcc6)",
        "on-tertiary-container": "var(--on-tertiary-container, #fffbff)",
        "on-surface-variant": "var(--on-surface-variant, #424754)",
        "surface-container-highest": "var(--surface-container-highest, #dce2f7)",
        "background": "var(--background, #f9f9ff)",
        "inverse-on-surface": "var(--inverse-on-surface, #edf0ff)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant, #723600)",
        "secondary-container": "var(--secondary-container, #dce2f3)",
        "error": "var(--error, #ba1a1a)",
        "inverse-primary": "var(--inverse-primary, #adc6ff)",
        "on-primary-container": "var(--on-primary-container, #fefcff)",
        "on-error": "var(--on-error, #ffffff)",
        "on-background": "var(--on-background, #141b2b)",
        "on-error-container": "var(--on-error-container, #93000a)",
        "primary-fixed-dim": "var(--primary-fixed-dim, #adc6ff)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant, #404754)",
        "surface-bright": "var(--surface-bright, #f9f9ff)",
        "outline": "var(--outline, #727785)",
        "inverse-surface": "var(--inverse-surface, #293040)",
        "surface-container-low": "var(--surface-container-low, #f1f3ff)",
        "surface-container-lowest": "var(--surface-container-lowest, #ffffff)",
        "on-surface": "var(--on-surface, #141b2b)",
        "on-primary": "var(--on-primary, #ffffff)",
        "primary-fixed": "var(--primary-fixed, #d8e2ff)",
        "primary-container": "var(--primary-container, #2170e4)",
        "surface": "var(--surface, #f9f9ff)",
        "on-primary-fixed": "var(--on-primary-fixed, #001a42)",
        "tertiary-container": "var(--tertiary-container, #b75b00)",
        "border-light": "var(--border-light, #E5E7EB)",
        "primary": "var(--primary, #0058be)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant, #004395)",
        "error-container": "var(--error-container, #ffdad6)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed, #311400)",
        "surface-dim": "var(--surface-dim, #d3daef)",
        "on-secondary-container": "var(--on-secondary-container, #5e6572)",
        "surface-subtle": "var(--surface-subtle, #F8F9FA)",
        "obsidian": {
          900: '#0F1115',
          800: '#14171C',
          700: '#1A1D24',
        }
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-xl": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "label-sm": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
